<template>
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
  <circle cx="34.4378" cy="50" fill="#93dbe9" r="19">
    <animate attributeName="cx" repeatCount="indefinite" dur="2.380952380952381s" keyTimes="0;0.5;1" values="31;69;31" begin="-1.1904761904761905s"></animate>
  </circle>
  <circle cx="65.5622" cy="50" fill="#689cc5" r="19">
    <animate attributeName="cx" repeatCount="indefinite" dur="2.380952380952381s" keyTimes="0;0.5;1" values="31;69;31" begin="0s"></animate>
  </circle>
  <circle cx="34.4378" cy="50" fill="#93dbe9" r="19">
    <animate attributeName="cx" repeatCount="indefinite" dur="2.380952380952381s" keyTimes="0;0.5;1" values="31;69;31" begin="-1.1904761904761905s"></animate>
    <animate attributeName="fill-opacity" values="0;0;1;1" calcMode="discrete" keyTimes="0;0.499;0.5;1" dur="2.380952380952381s" repeatCount="indefinite"></animate>
  </circle>
  <!-- [ldio] generated by https://loading.io/ --></svg>
</template>
